In [1]:
from google_search_history import process
from pathlib import Path
import pandas as pd
import io

In [2]:
output = process(Path('tests/data/takeout.zip'))

    With this research we want to invesitgate how news consumption has changed during/after the COVID-19 related Dutch
    curfew. To examine this, we looked at your Google Search History. First, we divided your browser history into three
    periods: before the start of the curfew (before 2021-01-23), during the curfew (between 2021-01-23 and 2021-04-28)
    and post curfew (after 2021-04-28). For each period, we counted how many times you searched for a news website
    versus any another type of website (i.e., news/other). While counting, we also took the time of day
    (i.e., morning/afternoon/evening/night) into account.

                          Searches
Website Curfew Time
news    before afternoon        21
               evening           8
               morning           8
               night            13
        during afternoon        27
               evening          31
               morning          20
               night            22
        post   afternoon        11
               evening           6
               morning          13
               night            20
other   before afternoon        73
               evening          55
               morning          79
               night            76
        during afternoon        72
               evening          55
               morning          54
               night            53
        post   afternoon        73
               evening          69
               morning          72
               night            69

    Your earliest web search was on 2020-10-20,
    The Dutch curfew took place between 2021-01-23 and 2021-04-28,
    Your latest web search was on 2021-07-22.

In [3]:
output['summary']

{'read_files': 'BrowserHistory.json',
 'earliest_search': datetime.date(2020, 10, 20),
 'start_curfew': datetime.date(2021, 1, 23),
 'end_curfew': datetime.date(2021, 4, 28),
 'latest_search': datetime.date(2021, 7, 22)}

In [4]:
output['data']

'Curfew,Website,Time,Searches\r\nbefore,news,morning,8\r\nbefore,news,afternoon,21\r\nbefore,news,evening,8\r\nbefore,news,night,13\r\nbefore,other,morning,79\r\nbefore,other,afternoon,73\r\nbefore,other,evening,55\r\nbefore,other,night,76\r\nduring,news,morning,20\r\nduring,news,afternoon,27\r\nduring,news,evening,31\r\nduring,news,night,22\r\nduring,other,morning,54\r\nduring,other,afternoon,72\r\nduring,other,evening,55\r\nduring,other,night,53\r\npost,news,morning,13\r\npost,news,afternoon,11\r\npost,news,evening,6\r\npost,news,night,20\r\npost,other,morning,72\r\npost,other,afternoon,73\r\npost,other,evening,69\r\npost,other,night,69\r\n'

In [5]:
overview = pd.read_csv(io.StringIO(output['data']), sep=",")
overview

    Curfew Website       Time  Searches
0   before    news    morning         8
1   before    news  afternoon        21
2   before    news    evening         8
3   before    news      night        13
4   before   other    morning        79
5   before   other  afternoon        73
6   before   other    evening        55
7   before   other      night        76
8   during    news    morning        20
9   during    news  afternoon        27
10  during    news    evening        31
11  during    news      night        22
12  during   other    morning        54
13  during   other  afternoon        72
14  during   other    evening        55
15  during   other      night        53
16    post    news    morning        13
17    post    news  afternoon        11
18    post    news    evening         6
19    post    news      night        20
20    post   other    morning        72
21    post   other  afternoon        73
22    post   other    evening        69
23    post   other      night        69

In [6]:
curf_web = overview.groupby(['Website']).sum()
curf_web['%'] = curf_web.apply(lambda x: x/x.sum())
curf_web

         Searches    %
Website
news          200  0.2
other         800  0.8

In [7]:
curf_web = overview.groupby(['Curfew', 'Website']).sum()
curf_web['%'] = curf_web.groupby(level=0).apply(lambda x: x/x.sum())
curf_web

                Searches         %
Curfew Website
before news           50  0.150150
       other         283  0.849850
during news          100  0.299401
       other         234  0.700599
post   news           50  0.150150
       other         283  0.849850

In [8]:
curf_time_web = overview.groupby(['Curfew', 'Time', 'Website']).sum()
curf_time_web['%'] = curf_time_web.groupby(['Curfew', 'Time']).apply(lambda x: x/x.sum())
curf_time_web

                          Searches         %
Curfew Time      Website
before afternoon news           21  0.223404
                 other          73  0.776596
       evening   news            8  0.126984
                 other          55  0.873016
       morning   news            8  0.091954
                 other          79  0.908046
       night     news           13  0.146067
                 other          76  0.853933
during afternoon news           27  0.272727
                 other          72  0.727273
       evening   news           31  0.360465
                 other          55  0.639535
       morning   news           20  0.270270
                 other          54  0.729730
       night     news           22  0.293333
                 other          53  0.706667
post   afternoon news           11  0.130952
                 other          73  0.869048
       evening   news            6  0.080000
                 other          69  0.920000
       morning   news           13  0.152941
                 other          72  0.847059
       night     news           20  0.224719
                 other          69  0.775281